CREATE TABLE Users
(
    Id INT IDENTITY(1,1) PRIMARY KEY,

    Name NVARCHAR(100) NOT NULL,

    Email NVARCHAR(150) NOT NULL UNIQUE,

    Password NVARCHAR(255) NOT NULL,

    Role NVARCHAR(20) NOT NULL,

    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Invoices
(
    InvoiceId INT IDENTITY(1,1) PRIMARY KEY,

    InvoiceNumber NVARCHAR(50) NOT NULL UNIQUE,

    CustomerName NVARCHAR(150) NOT NULL,

    Amount DECIMAL(18,2) NOT NULL,

    Status NVARCHAR(20) NOT NULL,

    CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);

SELECT * FROM Users;

SELECT * FROM Invoices;

DELETE FROM Invoices;

ALTER TABLE Invoices
ADD UserId INT NOT NULL;

ALTER TABLE Invoices
ADD CONSTRAINT FK_Invoices_Users
FOREIGN KEY (UserId) REFERENCES Users(Id);